# Generated by Django 6.0.2 on 2026-02-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ajustes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mantenimiento', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Ajustes',
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('AL_FUEGO', '🔥 AL FUEGO'), ('BURGUERS', 'BURGUERS'), ('PIZZAS', 'PIZZAS'), ('EMPANADAS', 'EMPANADAS'), ('POSTRES', 'POSTRES'), ('BEBIDAS', 'BEBIDAS')], default='AL_FUEGO', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='platos/')),
                ('es_vegetariano', models.BooleanField(default=False)),
                ('es_picante', models.BooleanField(default=False)),
                ('disponible', models.BooleanField(default=True)),
                ('en_oferta', models.BooleanField(default=False)),
                ('porcentaje_descuento', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=20)),
                ('metodo_entrega', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entregado', models.BooleanField(default=False)),
            ],
        ),
    ]
